### PR TITLE
feat: add saccade option, divide options into sections

### PR DESCRIPTION
**Pull request by dingxuanyao**
- saccade: https://github.com/ansh/bionic-reading/issues/39
- adding a divider to options for readability

preview: 
image

### CODE REVIEW

**Comment by X140Yu** [comment]
Hi @dingxuanyao Nice PR!

I have something to suggest:
- the saccade value default is undefined, can make it the default option eg. every word
image

- When the slide value changes, only a refresh & toggle can apply the effect, can we make it change on the fly?

**Comment by dingxuanyao** [comment]
@X140Yu 
> * the saccade value default is undefined, can make it the default option eg. every word

Should be fixed in new commit: https://github.com/ansh/bionic-reading/pull/44/files#diff-3c22697f71643bb8287c56e99e71595d2253122520883f9319e9b27140da5019R84-R87

> * When the slide value changes, only a refresh & toggle can apply the effect, can we make it change on the fly?

I'm not sure how to implement this other than forcing a refresh on the page. Do you have any other ideas?

**Comment by X140Yu** [comment]
@dingxuanyao 

>I'm not sure how to implement this other than forcing a refresh on the page. Do you have any other ideas?

I don't know if remove all the `<br-bold>` elements and re-apply the process will work, can give it a try

**Comment by asieduernest12** [comment]
i reimplmented the slider with my pull request so it should work fine without needing to reload the page

**Comment by X140Yu** [comment]
Hi @dingxuanyao , can take a look at PR #53

**Comment by dingxuanyao** [comment]
Closing in favour of https://github.com/ansh/bionic-reading/pull/53

**Pull request closed without merging**
