### PR TITLE
Fix issue#73 broken toggle

### PR DESCRIPTION
**Pull request by asieduernest12**
fix for issue #73 
@ansh @X140Yu can you take a look

Feat included onoff button
image

image

### CODE REVIEW

**Comment by asieduernest12** [comment]
https://github.com/ansh/bionic-reading/pull/77/commits/655f34e720d1e22854f676e1bd16f988fdd6efc0
Feat fixations strength slider with persistense

image

image

**Comment by X140Yu** [comment]
@asieduernest12 thanks for the PR

got some errors in the popup console 
image

**Comment by asieduernest12** [comment]
> @asieduernest12 thanks for the PR
> 
> got some errors in the popup console image

I have no idea i did not cause it but i have seen it happen on my machine just now.
```yarn dev:chrome``` does not work for me at all so i just build the production version and it is working fine

**Comment by asieduernest12** [comment]
@X140Yu @ansh popup issue reported by @X140Yu is fixed

the issue resulted from
runTimeHandler == typeof brower == 'undefined' ? chrome: browser

ideally that means
runTimeHandler is chrome most times 
so i used 
runTimeHandler in updates instead of chrome directly

it should work but it doesnt 

only the registration of a listerner will work with runTimeHandler

sending messages to a runtime script or tab requires

chrome.tabs.sendMessage and chrome.runtime.sendMessage

using
runTimeHandler.tabs.sendMessage or runTimeHandler.runtime.sendMessage will bug out

**Comment by X140Yu** [comment]
>using runTimeHandler.tabs.sendMessage or runTimeHandler.runtime.sendMessage will bug out

@asieduernest12 Thanks for pointing out the issue

Tested the PR and it works pretty great!

**Pull request merged**
