### PR TITLE
smaller words receive less bold, small style change

### PR DESCRIPTION
**Pull request by milkyomo**
added missing <body> tag, changed cursor to pointer on hover of toggle button, added midpoint condition so shorter words, such as "the", "and", "but", etc. receive less bold to improve visibility overall, which also stays true to the bionic reading example given by Bionic Reading.

### CODE REVIEW

**Comment by asieduernest12** [comment]
i like your fix, it clarifies the role of he buttons

**Comment by X140Yu** [comment]
Hi @milkyomo, thanks for the PR, can you only format the modified line? it's a lot easier to see where this PR actually changed, it can be done use a VSCode [setting](https://code.visualstudio.com/updates/v1_49#_only-format-modified-text)

**Comment by milkyomo** [comment]
> Hi @milkyomo, thanks for the PR, can you only format the modified line? it's a lot easier to see where this PR actually changed, it can be done use a VSCode [setting](https://code.visualstudio.com/updates/v1_49#_only-format-modified-text)

Thank you for this! So sorry about that :( I had to turn off my auto formatter

**Comment by X140Yu** [comment]
LGTM

**Pull request merged**
